### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fergalmonaghan** [faraday/wikiprep-esa#14]
Hi, sorry for the issue but I wasn't sure how else to contact you! I wanted to contact you to ask what reuse of wikiprep-esa is allowed or not?

As a separate request, perhaps you could also make the license more prominent to make re-use of the code easier for others?

Thanks very much for reading,
Fergal.

**Comment by faraday** [comment]
You can certainly reuse wikiprep-esa (that's actually the whole point).
I'll put up an appropriate LICENSE file soon.

**Comment by fergalmonaghan** [comment]
Great, thank you for the quick response! Was just concerned that certain 
proprietary commercial applications would not be allowed.
