### ISSUE TITLE
Runtime for sentence level features.

### ISSUE THREAD

**Issue by zhzhang** [faraday/wikiprep-esa#17]
Hello,

I am trying to reproduce the results from the 2006 paper "Overcoming the Brittleness Bottleneck..."
I am attempting to generate sentence level features by using TestESAVectors on individual sentences as input, but the total runtime for any of the corpuses look to be over 72 hours. Is this the amount of time it should take, and if not, how should I be processing the corpuses for sentence level features?

**Comment by faraday** [comment]
I used the implementation for enrich snippets (short text) so I don't have exact performance measurements for sentence level use.  However I think you can massively improve speed by caching result vectors for single words.

In the end, the single performance bottleneck for your sentence level client code should be averaging the vectors for your queries. For a natural language, word distribution will be quite suitable for caching. Please see Zipf's Law about this: https://en.wikipedia.org/wiki/Zipf%27s_law

> Thus the most frequent word will occur approximately twice as often as the second most frequent word, three times as often as the third most frequent word, etc.: the rank-frequency distribution is an inverse relation.

It should massively bring down the time spent for sentence processing.
