### ISSUE TITLE
scanData can't find Stemmer

### ISSUE THREAD

**Issue by dbk067** [faraday/wikiprep-esa#3]
scanData.py imports the Stemmer module, but I don't have it and I'm not sure which module this refers to. I've tried Google and PyPI with no luck.

**Comment by faraday** [comment]
Stemmer module is actually PyStemmer, which is the project encapsulating Python wrappers of Snowball:
You can find further info at: http://snowball.tartarus.org/download.php

**Comment by turian** [comment]
This belongs in the README, under DEPENDENCIES.
