### ISSUE TITLE
Use cElementTree to make everything faster and simpler

### ISSUE THREAD

**Issue by turian** [faraday/wikiprep-esa#6]
I would like to try wikiprep-esa, but it is currently waaay too slow. I was struggling with wikiprep-esa, but it seemed like it was going to take 10 days or more to run scan\* on a recent wikidump.
This was the case even when I used pyre2 (a FAST regex library).

I wrote the following code to read a wikiprep XML using cElementTree (which is a core library in Python 2.5):

```
https://github.com/turian/wikiprep-postprocess/blob/master/xmlwikiprep.py
```

This code reads the XML in a _streaming_ fashion (i.e. doesn't read everything into memory). I just ran over an entire wikiprep dump overnight.
So the code is much faster than the regex parsing you do. Also, cElementTree does buffering automatically, so the code is much cleaner and shorter too, and simpler to understand.

It would be great if you could use my code as inspiration for refactoring wikiprep-esa to use cElementTree. It would work VERY fast then.

**Comment by faraday** [comment]
I'll definitely try that, thank you!

**Comment by faraday** [comment]
directScan.py and addRedirects.py will also be modified.
