### ISSUE TITLE
tfidf table does not exist

### ISSUE THREAD

**Issue by xxsc2010** [faraday/wikiprep-esa#8]
I have encountered the same issue as mentioned  in Issue #4 by dbk067:

"I'm following the readme and I've just finished running IndexModifier with no errors. The next step is IndexPruner, but it seems to expect the tfidf table to exist before it can be run. IndexModifier claims it loads these values into the database, but it doesn't create the necessary table. Am I missing a step or is something else going on?"

Is there anyone knows how to solve it?

Thanks,

**Comment by faraday** [comment]
From README, Usage section:

"""
java -cp esa-lucene.jar edu.wiki.index.ESAWikipediaIndexer <Lucene index folder>

java -cp esa-lucene.jar edu.wiki.modify.IndexModifier <Lucene index folder>
... or, if you have a sufficient RAM (15 Gb was enough to process en-20090618 dump) try this instead:
java -cp esa-lucene.jar edu.wiki.modify.MemIndexModifier <Lucene index folder>

IndexModifier sorts TF-IDF vectors using sort utility of Unix, also using the disk.
MemIndexModifier handles sorting in memory instead.

Then perform a feature generation to test:

To generate regular features:
java -cp esa-lucene.jar edu.wiki.demo.TestESAVectors
"""

IndexPruner is currently NOT used for normal operation.
